/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AgentApplicationSchema extends BaseModel {
  static $columns = ['applicantUserId', 'createdAt', 'id', 'rejectionReason', 'reviewedAt', 'reviewedBy', 'sponsorAgentId', 'status', 'tier', 'updatedAt'] as const
  $columns = AgentApplicationSchema.$columns
  @column()
  declare applicantUserId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare rejectionReason: string | null
  @column.dateTime()
  declare reviewedAt: DateTime | null
  @column()
  declare reviewedBy: number | null
  @column()
  declare sponsorAgentId: number | null
  @column()
  declare status: string
  @column()
  declare tier: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AgentDeviceSchema extends BaseModel {
  static $columns = ['agentId', 'createdAt', 'deviceFingerprint', 'id', 'lastUsedAt', 'registeredAt', 'status', 'updatedAt'] as const
  $columns = AgentDeviceSchema.$columns
  @column()
  declare agentId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare deviceFingerprint: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare registeredAt: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AgentDocumentSchema extends BaseModel {
  static $columns = ['agentId', 'createdAt', 'documentType', 'fileRef', 'id', 'rejectionReason', 'reviewedAt', 'reviewedBy', 'status', 'updatedAt'] as const
  $columns = AgentDocumentSchema.$columns
  @column()
  declare agentId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare documentType: string
  @column()
  declare fileRef: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare rejectionReason: string | null
  @column.dateTime()
  declare reviewedAt: DateTime | null
  @column()
  declare reviewedBy: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AgentStatusHistorySchema extends BaseModel {
  static $columns = ['agentId', 'changedBy', 'changedById', 'createdAt', 'id', 'newStatus', 'previousStatus', 'reason'] as const
  $columns = AgentStatusHistorySchema.$columns
  @column()
  declare agentId: number
  @column()
  declare changedBy: string
  @column()
  declare changedById: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare newStatus: string
  @column()
  declare previousStatus: string
  @column()
  declare reason: string | null
}

export class AgentSchema extends BaseModel {
  static $columns = ['address', 'approvedAt', 'approvedBy', 'businessName', 'city', 'code', 'commissionRate', 'createdAt', 'dailyLimit', 'email', 'fullName', 'id', 'latitude', 'longitude', 'monthlyLimit', 'parentAgentId', 'perTransactionLimit', 'phone', 'region', 'status', 'suspendedAt', 'suspensionReason', 'terminatedAt', 'terminationReason', 'tier', 'updatedAt', 'userId', 'walletId'] as const
  $columns = AgentSchema.$columns
  @column()
  declare address: string | null
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare approvedBy: number | null
  @column()
  declare businessName: string | null
  @column()
  declare city: string | null
  @column()
  declare code: string
  @column()
  declare commissionRate: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare dailyLimit: bigint | number | null
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latitude: string | null
  @column()
  declare longitude: string | null
  @column()
  declare monthlyLimit: bigint | number | null
  @column()
  declare parentAgentId: number | null
  @column()
  declare perTransactionLimit: bigint | number | null
  @column()
  declare phone: string
  @column()
  declare region: string | null
  @column()
  declare status: string
  @column.dateTime()
  declare suspendedAt: DateTime | null
  @column()
  declare suspensionReason: string | null
  @column.dateTime()
  declare terminatedAt: DateTime | null
  @column()
  declare terminationReason: string | null
  @column()
  declare tier: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare walletId: number | null
}

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'actorId', 'actorType', 'after', 'before', 'correlationId', 'createdAt', 'deviceId', 'id', 'ipAddress', 'resourceId', 'resourceType', 'userAgent'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorId: number
  @column()
  declare actorType: string
  @column()
  declare after: any | null
  @column()
  declare before: any | null
  @column()
  declare correlationId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column()
  declare resourceId: string
  @column()
  declare resourceType: string
  @column()
  declare userAgent: string | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BusinessAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = BusinessAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BusinessApiKeySchema extends BaseModel {
  static $columns = ['businessId', 'createdAt', 'id', 'keyHash', 'keyPrefix', 'lastUsedAt', 'revokedAt', 'status', 'updatedAt'] as const
  $columns = BusinessApiKeySchema.$columns
  @column()
  declare businessId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare keyHash: string
  @column()
  declare keyPrefix: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BusinessSignupOtpSchema extends BaseModel {
  static $columns = ['attempts', 'consumedAt', 'createdAt', 'email', 'expiresAt', 'id', 'otpHash', 'updatedAt'] as const
  $columns = BusinessSignupOtpSchema.$columns
  @column()
  declare attempts: number
  @column.dateTime()
  declare consumedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare otpHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BusinessSchema extends BaseModel {
  static $columns = ['approvedAt', 'approvedBy', 'code', 'createdAt', 'email', 'id', 'loginAttempts', 'loginLockedUntil', 'name', 'password', 'phone', 'pinAttempts', 'pinHash', 'pinLockedUntil', 'pinResetExpiresAt', 'pinResetTokenHash', 'planId', 'planNextMaintenanceBillingAt', 'planPaymentStatus', 'planSubscribedAt', 'status', 'suspendedAt', 'suspensionReason', 'terminatedAt', 'terminationReason', 'updatedAt', 'walletId', 'webhookUrl'] as const
  $columns = BusinessSchema.$columns
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare approvedBy: number | null
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare loginAttempts: number | null
  @column.dateTime()
  declare loginLockedUntil: DateTime | null
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare phone: string
  @column()
  declare pinAttempts: number | null
  @column()
  declare pinHash: string | null
  @column.dateTime()
  declare pinLockedUntil: DateTime | null
  @column.dateTime()
  declare pinResetExpiresAt: DateTime | null
  @column()
  declare pinResetTokenHash: string | null
  @column()
  declare planId: number | null
  @column.dateTime()
  declare planNextMaintenanceBillingAt: DateTime | null
  @column()
  declare planPaymentStatus: string
  @column.dateTime()
  declare planSubscribedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime()
  declare suspendedAt: DateTime | null
  @column()
  declare suspensionReason: string | null
  @column.dateTime()
  declare terminatedAt: DateTime | null
  @column()
  declare terminationReason: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare walletId: number | null
  @column()
  declare webhookUrl: string | null
}

export class CardCustomerSchema extends BaseModel {
  static $columns = ['businessId', 'createdAt', 'id', 'provider', 'providerCustomerId', 'updatedAt', 'userId'] as const
  $columns = CardCustomerSchema.$columns
  @column()
  declare businessId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare provider: string
  @column()
  declare providerCustomerId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class CardProductSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'currencyCode', 'dailyTopupLimit', 'description', 'id', 'imageMimeType', 'imageRef', 'issuancePrice', 'maxActiveCards', 'maxBalance', 'monthlyTopupLimit', 'name', 'perTopupLimit', 'status', 'updatedAt'] as const
  $columns = CardProductSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currencyCode: string
  @column()
  declare dailyTopupLimit: bigint | number | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageMimeType: string | null
  @column()
  declare imageRef: string | null
  @column()
  declare issuancePrice: bigint | number
  @column()
  declare maxActiveCards: number | null
  @column()
  declare maxBalance: bigint | number | null
  @column()
  declare monthlyTopupLimit: bigint | number | null
  @column()
  declare name: string
  @column()
  declare perTopupLimit: bigint | number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CardSchema extends BaseModel {
  static $columns = ['balanceCache', 'brand', 'businessId', 'cardProductId', 'cardType', 'createdAt', 'currencyCode', 'failureReason', 'firstSix', 'id', 'lastFour', 'masked', 'provider', 'providerCardId', 'status', 'updatedAt', 'userId', 'walletId'] as const
  $columns = CardSchema.$columns
  @column()
  declare balanceCache: bigint | number
  @column()
  declare brand: string
  @column()
  declare businessId: number | null
  @column()
  declare cardProductId: number | null
  @column()
  declare cardType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currencyCode: string
  @column()
  declare failureReason: string | null
  @column()
  declare firstSix: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastFour: string | null
  @column()
  declare masked: string | null
  @column()
  declare provider: string
  @column()
  declare providerCardId: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare walletId: number
}

export class CurrencySchema extends BaseModel {
  static $columns = ['code', 'countryCode', 'createdAt', 'decimals', 'isActive', 'logoUrl', 'name', 'numericCode', 'sortOrder', 'symbol', 'updatedAt'] as const
  $columns = CurrencySchema.$columns
  @column({ isPrimary: true })
  declare code: string
  @column()
  declare countryCode: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare decimals: number
  @column()
  declare isActive: boolean
  @column()
  declare logoUrl: string | null
  @column()
  declare name: string
  @column()
  declare numericCode: string | null
  @column()
  declare sortOrder: number
  @column()
  declare symbol: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DisputeMessageSchema extends BaseModel {
  static $columns = ['authorId', 'authorType', 'body', 'createdAt', 'disputeId', 'id'] as const
  $columns = DisputeMessageSchema.$columns
  @column()
  declare authorId: number
  @column()
  declare authorType: string
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare disputeId: string
  @column({ isPrimary: true })
  declare id: number
}

export class DisputeSchema extends BaseModel {
  static $columns = ['assignedTo', 'createdAt', 'id', 'ledgerTransactionId', 'openedAt', 'raisedById', 'raisedByType', 'reason', 'resolutionNotes', 'resolutionTransactionId', 'resolvedAt', 'status', 'updatedAt'] as const
  $columns = DisputeSchema.$columns
  @column()
  declare assignedTo: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ledgerTransactionId: string
  @column.dateTime()
  declare openedAt: DateTime
  @column()
  declare raisedById: number
  @column()
  declare raisedByType: string
  @column()
  declare reason: string
  @column()
  declare resolutionNotes: string | null
  @column()
  declare resolutionTransactionId: string | null
  @column.dateTime()
  declare resolvedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExchangeRateSchema extends BaseModel {
  static $columns = ['createdAt', 'currencyCode', 'manualRate', 'marginBps', 'marketRate', 'marketSource', 'marketUpdatedAt', 'updatedAt'] as const
  $columns = ExchangeRateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare currencyCode: string
  @column()
  declare manualRate: string | null
  @column()
  declare marginBps: number
  @column()
  declare marketRate: string | null
  @column()
  declare marketSource: string | null
  @column.dateTime()
  declare marketUpdatedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FeeScheduleSchema extends BaseModel {
  static $columns = ['createdAt', 'feePercent', 'id', 'operationType', 'updatedAt', 'updatedBy'] as const
  $columns = FeeScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare feePercent: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare operationType: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: number | null
}

export class FxQuoteSchema extends BaseModel {
  static $columns = ['amountIn', 'amountOut', 'createdAt', 'expiresAt', 'fee', 'fromCurrency', 'fromWalletId', 'id', 'ledgerTransactionId', 'marginBps', 'midRate', 'ownerId', 'ownerType', 'rate', 'toCurrency', 'toWalletId', 'usedAt'] as const
  $columns = FxQuoteSchema.$columns
  @column()
  declare amountIn: bigint | number
  @column()
  declare amountOut: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare fee: bigint | number
  @column()
  declare fromCurrency: string
  @column()
  declare fromWalletId: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ledgerTransactionId: string | null
  @column()
  declare marginBps: number
  @column()
  declare midRate: string
  @column()
  declare ownerId: number
  @column()
  declare ownerType: string
  @column()
  declare rate: string
  @column()
  declare toCurrency: string
  @column()
  declare toWalletId: number
  @column.dateTime()
  declare usedAt: DateTime | null
}

export class IdempotencyKeySchema extends BaseModel {
  static $columns = ['actorId', 'actorType', 'createdAt', 'endpoint', 'expiresAt', 'id', 'key', 'requestHash', 'responseBody', 'responseStatus', 'status'] as const
  $columns = IdempotencyKeySchema.$columns
  @column()
  declare actorId: number
  @column()
  declare actorType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare endpoint: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare requestHash: string
  @column()
  declare responseBody: any | null
  @column()
  declare responseStatus: number | null
  @column()
  declare status: string
}

export class InternalAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = InternalAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InternalUserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'loginAttempts', 'loginLockedUntil', 'mfaEnabled', 'mfaLastUsedStep', 'mfaSecretEncrypted', 'mustChangePassword', 'password', 'status', 'updatedAt'] as const
  $columns = InternalUserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare loginAttempts: number | null
  @column.dateTime()
  declare loginLockedUntil: DateTime | null
  @column()
  declare mfaEnabled: boolean
  @column()
  declare mfaLastUsedStep: number | null
  @column()
  declare mfaSecretEncrypted: string | null
  @column()
  declare mustChangePassword: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class KycDocumentSchema extends BaseModel {
  static $columns = ['createdAt', 'documentType', 'id', 'kycVerificationId', 'mimeType', 'rawPayloadRef'] as const
  $columns = KycDocumentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare documentType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kycVerificationId: string
  @column()
  declare mimeType: string | null
  @column()
  declare rawPayloadRef: string
}

export class KycVerificationSchema extends BaseModel {
  static $columns = ['createdAt', 'decidedAt', 'decisionReason', 'expiresAt', 'id', 'provider', 'providerReference', 'reviewedBy', 'status', 'subjectId', 'subjectType', 'submittedAt', 'updatedAt', 'verificationType'] as const
  $columns = KycVerificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare decidedAt: DateTime | null
  @column()
  declare decisionReason: string | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare provider: string | null
  @column()
  declare providerReference: string | null
  @column()
  declare reviewedBy: number | null
  @column()
  declare status: string
  @column()
  declare subjectId: number
  @column()
  declare subjectType: string
  @column.dateTime()
  declare submittedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare verificationType: string
}

export class LedgerAccountSchema extends BaseModel {
  static $columns = ['accountType', 'code', 'createdAt', 'currencyCode', 'id', 'name', 'ownerId', 'ownerType', 'status', 'updatedAt'] as const
  $columns = LedgerAccountSchema.$columns
  @column()
  declare accountType: string
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currencyCode: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare ownerId: number | null
  @column()
  declare ownerType: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LedgerEntrySchema extends BaseModel {
  static $columns = ['amount', 'balanceAfter', 'createdAt', 'currencyCode', 'direction', 'id', 'ledgerAccountId', 'ledgerTransactionId'] as const
  $columns = LedgerEntrySchema.$columns
  @column()
  declare amount: bigint | number
  @column()
  declare balanceAfter: bigint | number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currencyCode: string
  @column()
  declare direction: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ledgerAccountId: number
  @column()
  declare ledgerTransactionId: string
}

export class LedgerTransactionSchema extends BaseModel {
  static $columns = ['amount', 'completedAt', 'correlationId', 'counterpartyPhone', 'createdAt', 'currencyCode', 'description', 'failureReason', 'fee', 'id', 'idempotencyKey', 'initiatedById', 'initiatedByType', 'metadata', 'paymentChannel', 'paymentMethod', 'provider', 'providerReferenceId', 'relatedTransactionId', 'reversalOfTransactionId', 'reversedAt', 'status', 'type', 'uuid'] as const
  $columns = LedgerTransactionSchema.$columns
  @column()
  declare amount: bigint | number | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare correlationId: string
  @column()
  declare counterpartyPhone: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currencyCode: string | null
  @column()
  declare description: string | null
  @column()
  declare failureReason: string | null
  @column()
  declare fee: bigint | number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare idempotencyKey: string | null
  @column()
  declare initiatedById: number
  @column()
  declare initiatedByType: string
  @column()
  declare metadata: any | null
  @column()
  declare paymentChannel: string | null
  @column()
  declare paymentMethod: string | null
  @column()
  declare provider: string | null
  @column()
  declare providerReferenceId: string | null
  @column()
  declare relatedTransactionId: string | null
  @column()
  declare reversalOfTransactionId: string | null
  @column.dateTime()
  declare reversedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare type: string
  @column()
  declare uuid: string
}

export class NotificationSchema extends BaseModel {
  static $columns = ['createdAt', 'data', 'id', 'message', 'readAt', 'recipientId', 'recipientType', 'title', 'type', 'updatedAt'] as const
  $columns = NotificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare data: any | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare recipientId: number
  @column()
  declare recipientType: string
  @column()
  declare title: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OutboxEventSchema extends BaseModel {
  static $columns = ['aggregateId', 'aggregateType', 'attempts', 'createdAt', 'eventType', 'id', 'payload', 'publishedAt', 'status'] as const
  $columns = OutboxEventSchema.$columns
  @column()
  declare aggregateId: string
  @column()
  declare aggregateType: string
  @column()
  declare attempts: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare payload: any
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare status: string
}

export class PlanSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'currencyCode', 'description', 'features', 'id', 'maintenancePrice', 'name', 'price', 'status', 'updatedAt'] as const
  $columns = PlanSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currencyCode: string
  @column()
  declare description: string | null
  @column()
  declare features: any
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare maintenancePrice: bigint | number
  @column()
  declare name: string
  @column()
  declare price: bigint | number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RiskAssessmentSchema extends BaseModel {
  static $columns = ['createdAt', 'decision', 'id', 'ledgerTransactionId', 'provider', 'providerReference', 'riskLevel', 'rulesTriggered', 'score'] as const
  $columns = RiskAssessmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare decision: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ledgerTransactionId: string
  @column()
  declare provider: string | null
  @column()
  declare providerReference: string | null
  @column()
  declare riskLevel: string
  @column()
  declare rulesTriggered: any | null
  @column()
  declare score: number
}

export class UserSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'email', 'fullName', 'id', 'loginAttempts', 'loginLockedUntil', 'password', 'pinAttempts', 'pinHash', 'pinLockedUntil', 'pinResetExpiresAt', 'pinResetTokenHash', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare code: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare loginAttempts: number | null
  @column.dateTime()
  declare loginLockedUntil: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare pinAttempts: number | null
  @column()
  declare pinHash: string | null
  @column.dateTime()
  declare pinLockedUntil: DateTime | null
  @column.dateTime()
  declare pinResetExpiresAt: DateTime | null
  @column()
  declare pinResetTokenHash: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WalletSchema extends BaseModel {
  static $columns = ['agentId', 'balanceCache', 'businessId', 'createdAt', 'currencyCode', 'dailyLimit', 'id', 'ledgerAccountId', 'lockVersion', 'monthlyLimit', 'perTransactionLimit', 'status', 'updatedAt', 'userId'] as const
  $columns = WalletSchema.$columns
  @column()
  declare agentId: number | null
  @column()
  declare balanceCache: bigint | number
  @column()
  declare businessId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currencyCode: string
  @column()
  declare dailyLimit: bigint | number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ledgerAccountId: number
  @column()
  declare lockVersion: number
  @column()
  declare monthlyLimit: bigint | number | null
  @column()
  declare perTransactionLimit: bigint | number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class WebhookDeliverySchema extends BaseModel {
  static $columns = ['createdAt', 'eventType', 'id', 'lastError', 'nextRetryAt', 'payload', 'retryCount', 'status', 'subscriptionId', 'updatedAt'] as const
  $columns = WebhookDeliverySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare eventType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastError: string | null
  @column.dateTime()
  declare nextRetryAt: DateTime | null
  @column()
  declare payload: any
  @column()
  declare retryCount: number | null
  @column()
  declare status: string | null
  @column()
  declare subscriptionId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WebhookSubscriptionSchema extends BaseModel {
  static $columns = ['active', 'businessId', 'createdAt', 'events', 'id', 'secret', 'updatedAt', 'url', 'userId'] as const
  $columns = WebhookSubscriptionSchema.$columns
  @column()
  declare active: boolean | null
  @column()
  declare businessId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare events: any
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare secret: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
  @column()
  declare userId: number | null
}
